name: Unpack and Build APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip '*.zip' -d appsrc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev \
            python3-pip python3-setuptools python3-venv zip unzip openjdk-17-jdk
          pip install --user buildozer cython

      - name: Build APK
        run: |
          cd appsrc
          if [ ! -f buildozer.spec ]; then ~/.local/bin/buildozer init; fi
          ~/.local/bin/buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: appsrc/bin/*.apk
